### PR TITLE
Fix Gradio Demo

### PR DESCRIPTION
**Pull request by freddyaboulton**
When streaming audio, the data must be either in bytes or a file not a tuple. 

I think this is something we can fix in core gradio. 

Also updated the demo to use the Gradio 5.0 pre-release. No breaking changes compared to Gradio 4 for this demo but under-the-hood Gradio 5 is a lot better for streaming media. Official release in about 2 weeks.

BTW this model is incredible. It's so fast. Can you share the steps to train such a model and make it so fast? Would be great for the community. 

https://github.com/user-attachments/assets/6b2d9a9a-82ca-4517-bd9d-ae86e80ef831

### CODE REVIEW

**Comment by thewh1teagle** [comment]
> When streaming audio, the data must be either in bytes or a file, not a tuple.

Some extra documentation on this might help!

> Also updated the demo to use the Gradio 5.0 pre-release. No breaking changes compared to Gradio 4 for this demo, but Gradio 5 is much better for streaming media. Official release in about 2 weeks.

I tested it out, and it works great overall! Just a couple of things:

- We're now relying on `ffmpeg`. I'd rather use native Python compression like `ogg` instead of streaming, since streaming still takes a bit to load on slower networks (like 3G). You can see this by enabling the throttle option in the network tab of the browser console.
  
- The streaming UI isn't quite as intuitive as the previous version with the wave animation—I found the old one easier to use.

Really appreciate the PR! Feel free to tweak things if you'd like, but no worries if not—I can take it from here. The final PR will still include co-authorship :)

> BTW, the model is amazing—so fast! Would you mind sharing how you trained it to get that speed? The community would love to know!

Glad you think so! My focus was to keep it simple, lightweight, and fast, while balancing quality. I might write a Medium post on it soon, but for now, most of the info is in the repo, and I’ve documented most of it.

Thanks again for your help and contribution!

**Comment by thewh1teagle** [comment]
I found that this one works by compressing it with mp3 and doesn't require ffmpeg:


```python
import soundfile as sf

def create(text: str, rate, pitch, energy):
    if not text_has_niqqud(text):
        text = niqqud_model.compute(text)
    waveforms = []
    for segment in segment_extractor.extract_segments(text):
        waveform = speech_model.create(segment.text, rate=rate, pitch=pitch, energy=energy)
        waveforms.append(waveform.samples)
        silence = segment.create_pause(waveform.sample_rate)
        waveforms.append(silence)
    waveform = np.concatenate(waveforms)
    
    buf = io.BytesIO()
    sf.write(buf, waveform, speech_model.sample_rate, format='ogg')
    buf.seek(0)
    return buf.read()
```

The response may be slightly slower due to the conversion, but this trade-off is worth it for slower networks. Additionally, there is another issue: the downloaded file currently lacks an extension.

**Comment by freddyaboulton** [comment]
Switched to the implementation you suggested @thewh1teagle !

> the downloaded file currently lacks an extension

When returning bytes, gradio doesn't know what extension to save it to so that's what's happening. We can return a file instead.

> The streaming UI isn't quite as intuitive as the previous version with the wave animation—I found the old one easier to use.

I'll see if we can enable the waveform while streaming in the gradio side.

> Some extra documentation on this might help!

Revamping the docs on this as we speak

**Comment by thewh1teagle** [comment]
> When returning bytes, gradio doesn't know what extension to save it to so that's what's happening. We can return a file instead.

What if we'd return BytesIO buffer? It has `name` attribute for this exact purpose
That should be more efficient to return it from the memory directly instead of reading and writing to disk, not sure if gradio audio element supports it

**Comment by freddyaboulton** [comment]
>  It has name attribute for this exact purpose

Does it? I can't find it in the docs. But in any event we would have to make that change into gradio core. Not against it but wouldn't fix the issue with the file extension for this demo.

**Comment by thewh1teagle** [comment]
I plan to switch to streaming once Gradio supports it with a similar UI and becomes more stable for real-time streaming.
I also decided to remove the conversion to ogg, as the drop in quality was noticeable. 

Hopefully, the model will eventually reach a level where compression won't be an issue :)
I’ve gathered the helper functions from the PR and resolved the audio normalization.

Thanks for contribution!

**Pull request merged**
